# Generated by Django 2.0.1 on 2018-01-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='displayType',
            field=models.IntegerField(choices=[(0, 'Integer Number'), (2, 'Binary, Yes/No'), (1, 'Floating Point Number')], default=1, verbose_name='Readings Format'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='displayUnits',
            field=models.CharField(choices=[('MWh', 'Power: MegaWatt Hours'), ('Wh', 'Power: Watt Hours'), ('kW', 'Power: KiloWatts'), ('BYN', 'Binary: Yes/No'), ('V', 'Voltage: Volts'), ('kWh', 'Power: KiloWatt Hours'), ('W', 'Power: Watts'), ('C', 'Temp: Celsius'), ('K', 'Temp: Kelvin'), ('A', 'Current: Amps'), ('%', 'Math: Percentage'), ('BAI', 'Binary: Active/Inactive'), ('mV', 'Voltage: milliVolts'), ('mW', 'Power: milliWatts'), ('BPN', 'Binary: Present/Missing'), ('MW', 'Power: MegaWatts'), ('mWh', 'Energy: milliWatt Hours'), ('mA', 'Current: milliAmps'), ('NUM', 'Generic: Number'), ('BOO', 'Binary: On/Off'), ('F', 'Temp: Farenhiet')], default='NUM', max_length=3, verbose_name='Readings Units'),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='displayType',
            field=models.IntegerField(choices=[(0, 'Integer Number'), (2, 'Binary, Yes/No'), (1, 'Floating Point Number')], default=1, verbose_name='Diplay Format'),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='displayUnits',
            field=models.CharField(choices=[('MWh', 'Power: MegaWatt Hours'), ('Wh', 'Power: Watt Hours'), ('kW', 'Power: KiloWatts'), ('BYN', 'Binary: Yes/No'), ('V', 'Voltage: Volts'), ('kWh', 'Power: KiloWatt Hours'), ('W', 'Power: Watts'), ('C', 'Temp: Celsius'), ('K', 'Temp: Kelvin'), ('A', 'Current: Amps'), ('%', 'Math: Percentage'), ('BAI', 'Binary: Active/Inactive'), ('mV', 'Voltage: milliVolts'), ('mW', 'Power: milliWatts'), ('BPN', 'Binary: Present/Missing'), ('MW', 'Power: MegaWatts'), ('mWh', 'Energy: milliWatt Hours'), ('mA', 'Current: milliAmps'), ('NUM', 'Generic: Number'), ('BOO', 'Binary: On/Off'), ('F', 'Temp: Farenhiet')], default='NUM', max_length=3, verbose_name='Display Units'),
        ),
    ]
