# Generated by Django 2.0.1 on 2018-01-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0003_auto_20180115_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='readingFloat',
            field=models.FloatField(blank=True, null=True, verbose_name='Floating Point Reading'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='readingInt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Integer Reading'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='displayType',
            field=models.IntegerField(choices=[(1, 'Floating Point Number'), (0, 'Integer Number'), (2, 'Binary, Yes/No')], default=1, verbose_name='Readings Format'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='displayUnits',
            field=models.CharField(choices=[('mA', 'Current: milliAmps'), ('BYN', 'Binary: Yes/No'), ('Wh', 'Power: Watt Hours'), ('BAI', 'Binary: Active/Inactive'), ('BOO', 'Binary: On/Off'), ('mV', 'Voltage: milliVolts'), ('V', 'Voltage: Volts'), ('F', 'Temp: Farenhiet'), ('C', 'Temp: Celsius'), ('kWh', 'Power: KiloWatt Hours'), ('A', 'Current: Amps'), ('NUM', 'Generic: Number'), ('BPN', 'Binary: Present/Missing'), ('%', 'Math: Percentage'), ('K', 'Temp: Kelvin'), ('mWh', 'Energy: milliWatt Hours'), ('MW', 'Power: MegaWatts'), ('kW', 'Power: KiloWatts'), ('W', 'Power: Watts'), ('MWh', 'Power: MegaWatt Hours'), ('mW', 'Power: milliWatts')], default='NUM', max_length=3, verbose_name='Readings Units'),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='displayType',
            field=models.IntegerField(choices=[(1, 'Floating Point Number'), (0, 'Integer Number'), (2, 'Binary, Yes/No')], default=1, verbose_name='Diplay Format'),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='displayUnits',
            field=models.CharField(choices=[('mA', 'Current: milliAmps'), ('BYN', 'Binary: Yes/No'), ('Wh', 'Power: Watt Hours'), ('BAI', 'Binary: Active/Inactive'), ('BOO', 'Binary: On/Off'), ('mV', 'Voltage: milliVolts'), ('V', 'Voltage: Volts'), ('F', 'Temp: Farenhiet'), ('C', 'Temp: Celsius'), ('kWh', 'Power: KiloWatt Hours'), ('A', 'Current: Amps'), ('NUM', 'Generic: Number'), ('BPN', 'Binary: Present/Missing'), ('%', 'Math: Percentage'), ('K', 'Temp: Kelvin'), ('mWh', 'Energy: milliWatt Hours'), ('MW', 'Power: MegaWatts'), ('kW', 'Power: KiloWatts'), ('W', 'Power: Watts'), ('MWh', 'Power: MegaWatt Hours'), ('mW', 'Power: milliWatts')], default='NUM', max_length=3, verbose_name='Display Units'),
        ),
    ]
